config/routes.rb
Rails.application.routes.draw do
  resources :photos
  root 'photos#new'

end

app/models/photo.rb
class Photo < ActiveRecord::Base

  mount_uploader :image, ImageUploader
  serialize :tags, JSON
  validates_presence_of :title, :image

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
require 'imagga'
class PhotosController < ApplicationController

  def index
    @photos = Photo.order("created_at desc").to_a
  end

  def new
    @photo = Photo.new(:title => "My photo \##{1 + (Photo.maximum(:id) || 0)}")
    if unsigned_mode?
      @unsigned = true
      # make sure we have the appropriate preset
      @preset_name = "sample_" + Digest::SHA1.hexdigest(Cloudinary.config.api_key + Cloudinary.config.api_secret)
      # @preset_name = "sample_" + Digest::SHA1.hexdigest(ENV['cloudinary_api_key'] + ENV['cloudinary_api_secret'])
      begin
        preset = Cloudinary::Api.upload_preset(@preset_name)
        if !preset["settings"]["return_delete_token"]
          Cloudinary::Api.update_upload_preset(@preset_name, :return_delete_token=>true)
        end
      rescue
        # An upload preset may contain (almost) all parameters that are used in upload. The following is just for illustration purposes
        Cloudinary::Api.create_upload_preset(:name => @preset_name, :unsigned => true, :folder => "preset_folder", :return_delete_token=>true)
      end
    end
    render view_for_new
  end

  def create
    @photo = Photo.new(photo_params)
    # In through-the-server mode, the image is first uploaded to the Rails server.
    # When @photo is saved, Carrierwave uploads the image to Cloudinary.
    # The upload metadata (e.g. image size) is then available in the
    # uploader object of the model (@photo.image).
    # In direct mode, the image is uploaded to Cloudinary by the browser,
    # and upload metadata is available in JavaScript (see new_direct.html.erb).
    if !@photo.save
      @error = @photo.errors.full_messages.join('. ')
      render view_for_new
      return
    end
    if !direct_upload_mode?
      # In this sample, we want to store a part of the upload metadata
      # ("bytes" - the image size) in the Photo model.
      # In direct mode, we pass the image size via a hidden form field
      # filled by JavaScript (see new_direct.html.erb).
      # In through-the-server mode, we need to copy this field from Cloudinary
      # upload metadata. The metadata is only available after Carrierwave
      # performs the upload (in @photo.save), so we need to update the
      # already saved photo here.
      @photo.update_attributes(:bytes => @photo.image.metadata['bytes'])
      # Show upload metadata in the view
      @upload = @photo.image.metadata
    end
    imagga = Imagga.new({image_url: @photo.image.url})
    imagga.tag
    @photo.tags = imagga.tags
    @photo.save
    redirect_to @photo
  end

  def show
    @photo = Photo.find(params[:id])
  end

  protected

  def direct_upload_mode?
    params[:direct].present?
  end

  def unsigned_mode?
    params[:unsigned].present?
  end

  def view_for_new
    direct_upload_mode? ? "new_direct" : "new"
  end

  private

  def photo_params
    params.require(:photo).permit(:title, :image, :image_cache, :bytes)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuantifiedSelfie</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/create.html.erb
<h1>Your photo was uploaded sucessfully!</h1>



<div class="photo">
  <h2><%= @photo.title %></h2>
  <a href="<%= @photo.image.url %>" target="_blank">
    <%= image_tag(@photo.image.thumbnail.url, :class => "thumbnail inline") %>
  </a>
</div>

<a href="<%= photos_path %>" class="back_link">Back to list</a>

<% if @upload %>
  <div class="upload_details">
    <h2>Upload metadata:</h2>
    <table>
      <% @upload.each_pair do |k, v| %>
        <tr><td><%= k %></td><td><%= v.to_json %></td></tr>
      <% end %>
    </table>
  </div>
<% end %>

<div class="tags">
  <h3>Loading tags...</h3>
</div>

app/views/photos/index.html.erb
<h1>Quantified Selfies</h1>

<p>
  It's time to get selfie analytics.
</p>

<p>
  All of the images you see here are transformed and served by Cloudinary.
</p>

<h1>Your Photos</h1>

<div class="actions">
  <a class="upload_link" href="<%= new_photo_path %>">Add photo</a>
  <a class="upload_link" href="<%= new_photo_path(:direct => true) %>">Add photo (direct upload)</a>
  <a class="upload_link" href="<%= new_photo_path(:direct => true, :unsigned => true) %>">Add photo (unsigned direct upload)</a>
</div>

<div class="photos">
  <% if @photos.empty? %>
    <br /><p>No photos were added yet.</p>
  <% end %>

  <% thumbs_params = { :format => "jpg", :height => 150, :width => 150, :class => "thumbnail inline" } %>
  <% @photos.each do |photo| %>
    <div class="photo">
      <h2><%= photo.title %></h2>
      <a href="<%= photo.image.url %>" target="_blank">
        <%= image_tag(photo.image.thumbnail.url, :class => "thumbnail inline") %>
      </a>

      <div class="less_info">
        <a href="#" class="toggle_info">Show transformations</a>
      </div>

      <div class="more_info">
        <a href="#" class="toggle_info">Hide transformations</a>
        <table class="thumbnails">
          <% transformations = [
              { :crop => "fill", :radius => 10, :height => 150, :width => 150 },
              { :crop => "scale", :height => 150, :width => 150 },
              { :crop => "fit", :height => 150, :width => 150 },
              { :crop => "thumb", :gravity => "face", :height => 150, :width => 150 },
              { :format => "png", :angle => 20, :transformation => {
                :crop => "fill", :gravity => "north", :effect => "sepia", :height => 150, :width => 150 } }
            ] %>
          <% transformations.each do |image_params| %>
            <td>
              <div class="thumbnail_holder">
                <a target="_blank" href="<%= cloudinary_url(photo.image, image_params.dup) %>" >
                  <%= cl_image_tag(photo.image, image_params.merge(:class => "thumbnail inline")) %>
                </a>
              </div>
              <table class="info">
                <% image_params.each_pair do |key, value| %>
                  <tr>
                    <td><%= key %></td>
                    <td><%= value.to_json %></td>
                  </tr>
                <% end %>
              </table>
              <br/>
            </td>
          <% end %>
        </table>

        <div class="note">
          Take a look at our documentation of <a href="http://cloudinary.com/documentation/image_transformations" target="_blank">Image Transformations</a> for a full list of supported transformations.
        </div>
      </div>
    </div>
  <% end %>
</div>

<script type='text/javascript'>
  $('.toggle_info').click(function () {
    $(this).closest('.photo').toggleClass('show_more_info');
    return false;
  });
</script>

app/views/photos/new.html.erb
<div id='backend_upload'>
  <div id='header'>
    <img src='<%= asset_path "QS_Logo.png" %>' class='logo'>
    <h1>Quantified Selfies</h1>
    <p><em>A Dem Boyz production</em></p>
  </div>

  <div class='image_upload'>
    <h3>Upload an image, get your tags!</h3>
    <%= form_for(@photo, :url => photos_path) do |f| %>
      <div class="form_line">
        <%= f.label :title, "Title:" %>
        <div class="form_controls">
          <%= f.text_field :title %>
        </div>
      </div>
      <div class="form_line">
        <%= f.label :image, "Image:" %>
        <div class="form_controls">
          <%= f.file_field :image %>
          <%= f.hidden_field(:image_cache) %>
        </div>
      </div>
      <div class="form_line">
        <div class="form_controls">
          <%= f.submit "Submit Photo" %>
          <% if @error %><span class="error"><%= @error %></span><% end %>
        </div>
      </div>
      <%= hidden_field_tag :direct, params[:direct] %>
    <% end %>
  </div>
  <a href="<%= photos_path %>" class="back_link">Back to list</a>
</div>

app/views/photos/show.html.erb
<div id="show_photo">
  <h2><%= @photo.title %></h2>
  <a href="<%=@photo.image_url %>" target="_blank"><img src="<%= @photo.image_url %>" class="result-img"></a>
  <h3>Your tagging results: </h3>
  <% @photo.tags.each do |tag, confidence| %>
    <p>Tag: <b><%= tag %></b>, confidence: <%= confidence %></p>
  <% end %>
</div>